## tl;dr

The seven-day GSC page snapshot contains 250 visible page rows, of which 139 are classified as transaction-oriented by URL pattern. The most actionable sales growth is **ranking lift for bike rentals** and **intent/snippet cleanup for airport and route pages**. The separate 28-day query export shows 10,320 impressions on direct-commercial queries at 4.37% CTR, but 7,589 (73.5%) of those commercial impressions are bike/scooty rental demand.

The large page-average opportunities are not all sales opportunities: distance-only queries generated 32,485 impressions at 0.88% CTR, and sunrise/sunset noise generated 371,407 impressions at 0.01% CTR. Those impressions should not be used to judge sales-page CTR or to choose commercial owners.

## Context & Methods

This is a decision-support analysis for the Kashi Taxi sales/SEO team. The controlling page source is the pasted Google Search Console seven-day export covering **31 August–6 September 2026**. A local 28-day GSC export covering **4–31 August 2026** is used only as a persistence and query-intent check.

### Key Assumptions

- “Sales page” means a URL whose path clearly describes taxi/cab/fare/booking, rental, tour package, tempo traveller, accommodation, or a bookable boat product. Editorial event, weather, safety, timing, and general guide URLs are excluded.
- “Direct commercial” queries contain a transaction signal such as taxi, cab, fare, rent, rental, booking, package, tempo traveller, hire, hotel, or dharamshala. “Distance-only” queries contain distance/duri/km wording without a transaction signal.
- The GSC page and query exports are separate dimensions. No page is credited with a specific query unless the page path/content and the query cluster align directionally; cannibalization findings are therefore architecture hypotheses to confirm in a page × query export.

## Data

The analysis loads the pasted page table, the latest local 28-day page export, and its 1,000-row query export. It writes bounded CSV companions in this folder for inspection.

In [1]:
from pathlib import Path
import sys
import pandas as pd

analysis_dir = Path.cwd() / 'analysis'
shortlist = pd.read_csv(analysis_dir / 'seo-sales-page-shortlist-2026-09-09.csv')
intent_summary = pd.read_csv(analysis_dir / 'gsc-query-intent-summary-2026-08-04-to-2026-08-31.csv')
cluster_summary = pd.read_csv(analysis_dir / 'gsc-query-cluster-summary-2026-08-04-to-2026-08-31.csv')
shortlist.head(14)

,url,path,clicks_7d,impressions_7d,ctr_7d,position_7d,clicks_28d,impressions_28d,ctr_28d,position_28d,priority,action,confidence
0,https://www.kashitaxi.in/bike-rentals-varanasi,/bike-rentals-varanasi,129,3978,0.032,6.1,549,16933,0.0324,6.06,P1,Rank lift,High
1,https://www.kashitaxi.in/hi/varanasi-to-vindhy...,/hi/varanasi-to-vindhyachal-taxi,24,3328,0.007,5.5,184,24219,0.0076,5.72,P1,Consolidate Hindi cluster,High
2,https://www.kashitaxi.in/en/city/varanasi/taxi...,/en/city/varanasi/taxi/varanasi-airport-to-var...,22,2869,0.008,5.2,65,10542,0.0062,5.83,P1,Intent repair + CTR,High
3,https://www.kashitaxi.in/en/varanasi-to-vindhy...,/en/varanasi-to-vindhyachal-taxi,28,2444,0.011,5.9,103,16760,0.0061,6.24,P1,Consolidate + retarget,High
4,https://www.kashitaxi.in/en/city/varanasi/taxi...,/en/city/varanasi/taxi/varanasi-airport-to-kas...,38,2332,0.016,4.3,68,12101,0.0056,5.28,P1,CTR + sales-intent focus,High
5,https://www.kashitaxi.in/en/varanasi-to-ayodhy...,/en/varanasi-to-ayodhya-taxi,5,1355,0.004,8.3,37,3817,0.0097,11.42,P1,Consolidate + sales-query rank,High
6,https://www.kashitaxi.in/en/city/varanasi/taxi...,/en/city/varanasi/taxi/varanasi-airport-to-ban...,5,1253,0.004,6.8,13,5175,0.0025,7.18,P1,Intent cleanup,High
7,https://www.kashitaxi.in/en/city/varanasi/taxi...,/en/city/varanasi/taxi/varanasi-to-gaya-taxi-s...,0,797,0.000,8.8,2,2873,0.0007,9.27,P1,Consolidate + retarget,High
8,https://www.kashitaxi.in/en/city/varanasi/sigh...,/en/city/varanasi/sightseeing/varanasi-local-s...,23,537,0.043,5.5,73,2126,0.0343,6.34,P1,Rank lift,High
9,https://www.kashitaxi.in/en/varanasi-to-ayodhy...,/en/varanasi-to-ayodhya-tempo-traveller,7,136,0.051,5.2,25,592,0.0422,6.17,P1,Rank lift,High
10,https://www.kashitaxi.in/en/city/nepal/taxi/va...,/en/city/nepal/taxi/varanasi-to-nepal-taxi,5,739,0.007,3.5,29,3112,0.0093,4.93,P2,Intent repair,High
11,https://www.kashitaxi.in/en/force-urbania-hire...,/en/force-urbania-hire-varanasi,2,495,0.004,2.4,10,1829,0.0055,2.69,P2,Intent repair,High
12,https://www.kashitaxi.in/en/varanasi-to-prayag...,/en/varanasi-to-prayagraj-taxi,5,237,0.021,9.4,21,2515,0.0083,9.09,P2,Sales-query rank lift,Medium
13,https://www.kashitaxi.in/en/senior-citizen-var...,/en/senior-citizen-varanasi-tour-package,4,150,0.027,7.0,25,555,0.0450,7.41,P2,Rank lift,Medium

## Results

The shortlist below deliberately mixes true sales opportunities with high-volume intent-repair cases so the team does not mistake a good page average for good commercial visibility.

In [2]:
shortlist[['priority','action','confidence','path','clicks_7d','impressions_7d','ctr_7d','position_7d','clicks_28d','impressions_28d','ctr_28d','position_28d']]

,priority,action,confidence,path,clicks_7d,impressions_7d,ctr_7d,position_7d,clicks_28d,impressions_28d,ctr_28d,position_28d
0,P1,Rank lift,High,/bike-rentals-varanasi,129,3978,0.032,6.1,549,16933,0.0324,6.06
1,P1,Consolidate Hindi cluster,High,/hi/varanasi-to-vindhyachal-taxi,24,3328,0.007,5.5,184,24219,0.0076,5.72
2,P1,Intent repair + CTR,High,/en/city/varanasi/taxi/varanasi-airport-to-var...,22,2869,0.008,5.2,65,10542,0.0062,5.83
3,P1,Consolidate + retarget,High,/en/varanasi-to-vindhyachal-taxi,28,2444,0.011,5.9,103,16760,0.0061,6.24
4,P1,CTR + sales-intent focus,High,/en/city/varanasi/taxi/varanasi-airport-to-kas...,38,2332,0.016,4.3,68,12101,0.0056,5.28
5,P1,Consolidate + sales-query rank,High,/en/varanasi-to-ayodhya-taxi,5,1355,0.004,8.3,37,3817,0.0097,11.42
6,P1,Intent cleanup,High,/en/city/varanasi/taxi/varanasi-airport-to-ban...,5,1253,0.004,6.8,13,5175,0.0025,7.18
7,P1,Consolidate + retarget,High,/en/city/varanasi/taxi/varanasi-to-gaya-taxi-s...,0,797,0.000,8.8,2,2873,0.0007,9.27
8,P1,Rank lift,High,/en/city/varanasi/sightseeing/varanasi-local-s...,23,537,0.043,5.5,73,2126,0.0343,6.34
9,P1,Rank lift,High,/en/varanasi-to-ayodhya-tempo-traveller,7,136,0.051,5.2,25,592,0.0422,6.17
10,P2,Intent repair,High,/en/city/nepal/taxi/varanasi-to-nepal-taxi,5,739,0.007,3.5,29,3112,0.0093,4.93
11,P2,Intent repair,High,/en/force-urbania-hire-varanasi,2,495,0.004,2.4,10,1829,0.0055,2.69
12,P2,Sales-query rank lift,Medium,/en/varanasi-to-prayagraj-taxi,5,237,0.021,9.4,21,2515,0.0083,9.09
13,P2,Rank lift,Medium,/en/senior-citizen-varanasi-tour-package,4,150,0.027,7.0,25,555,0.0450,7.41

In [3]:
intent_summary.sort_values('impressions', ascending=False)

,intent,query_rows,clicks,impressions,ctr,weighted_position
0,Sunrise/sunset noise,33,45,371407,0.000121,11.019308
1,Other informational,637,1295,92333,0.014025,7.301075
2,Distance-only,204,286,32485,0.008804,6.125411
3,Direct commercial,126,451,10320,0.043702,6.326289

In [4]:
cluster_summary.sort_values(['cluster','impressions'], ascending=[True,False]).head(40)

,cluster,intent,query_rows,clicks,impressions,ctr,weighted_position
0,Airport and railway stations,Distance-only,14,26,2366,0.010989,4.308204
1,Airport and railway stations,Other informational,3,6,480,0.012500,5.239229
2,Airport and railway stations,Direct commercial,1,1,54,0.018519,10.590000
3,Airport to Kashi Vishwanath,Distance-only,13,26,2791,0.009316,4.161096
4,Airport to Kashi Vishwanath,Other informational,6,11,1070,0.010280,4.564860
5,Airport to Kashi Vishwanath,Direct commercial,1,3,120,0.025000,3.630000
6,Ayodhya,Distance-only,21,23,2042,0.011263,8.466141
7,Ayodhya,Direct commercial,6,8,99,0.080808,3.969697
8,Ayodhya,Other informational,2,3,20,0.150000,3.098000
9,Bike rental,Direct commercial,61,337,7589,0.044406,4.640920
10,Gaya or Bodhgaya,Distance-only,5,3,2120,0.001415,8.497075
11,Gaya or Bodhgaya,Other informational,2,3,67,0.044776,9.613582
12,Local sightseeing,Other informational,3,8,114,0.070175,21.970175
13,Local sightseeing,Direct commercial,5,12,97,0.123711,7.352474
14,Nepal,Distance-only,8,17,1548,0.010982,2.684567
15,Nepal,Other informational,1,1,1,1.000000,5.000000
16,Urbania,Other informational,4,6,1142,0.005254,1.018275
17,Vindhyachal,Distance-only,59,122,12057,0.010119,5.236604
18,Vindhyachal,Other informational,17,30,863,0.034762,7.108308
19,Vindhyachal,Direct commercial,11,21,425,0.049412,12.813882

## Takeaways

1. Make `/bike-rentals-varanasi` the first ranking-lift test: its 28-day query cluster is direct commercial, already ranks around positions 3–7, and converts impressions to clicks far better than distance-led clusters.
2. Rework airport route titles and first-screen copy around fare, pickup, vehicle, and booking. Keep one short distance answer, but do not lead with “distance” when the page is meant to sell a transfer.
3. Consolidate duplicate Gaya/Bodhgaya, Ayodhya, Vindhyachal, airport, and station URLs before adding more keywords. Assign one owner per exact route/vehicle intent, then use supporting pages for narrower variants and internal links.
4. Request a GSC page × query export for the next pass. It is the missing evidence needed to verify which URL owns each commercial query and to quantify cannibalization instead of inferring it from URL/content overlap.